--- # Playbook to show handlers

- hosts: all
  user: ansibleuser
  sudo: yes
  gather_facts: true

  tasks:
      - name: "Install Apache into Redhat servers"
        command: yum install -y httpd
        when: ansible_os_family == "RedHat"
        notify: Restart HTTPD

      - name: "Install Apache Ubuntu based servers"
        command: apt-get install -y apache2
        when: ansible_os_family == "Debian"
  
  handlers:
      - name: Restart HTTPD
        service: name=httpd state=restarted










   

