- hosts: all
  user: ansibleuser
  sudo: yes
  connection: ssh

  vars:
   passwd: $1$Somekey$h4GKFX.BkjXxrt4poX.fO/

  tasks:
   - name: "Creating users with encrypted passwords"
     user: name="manjunath" password={{passwd}}


